import os
import sys
import json
import pickle
import argparse
import numpy as np
import scipy.io

from feature_extraction import extract_features_from_signal

def predict_single_ecg(mat_file_path):
    print("=" * 65)
    print("           ECG ARRHYTHMIA STANDALONE INFERENCE ENGINE          ")
    print("=" * 65)

    # 1. Validate file existence
    if not os.path.exists(mat_file_path):
        print(f"❌ ERROR: File not found at path: '{mat_file_path}'")
        sys.exit(1)

    print(f"\n[1] Input File: {os.path.abspath(mat_file_path)}")

    # 2. Load .mat file and extract 'val' variable
    try:
        mat_data = scipy.io.loadmat(mat_file_path)
    except Exception as e:
        print(f"❌ ERROR: Failed to read .mat file '{mat_file_path}'. Error: {e}")
        sys.exit(1)

    if 'val' not in mat_data:
        print(f"❌ ERROR: Key 'val' missing in .mat file. Found keys: {[k for k in mat_data.keys() if not k.startswith('__')]}")
        sys.exit(1)

    raw_signal = mat_data['val'].squeeze().astype(np.float32)

    # 3. Validate signal length (must be exactly 3600 samples)
    if raw_signal.ndim != 1 or len(raw_signal) != 3600:
        print(f"❌ ERROR: Expected signal length of 3600 samples, but got shape {raw_signal.shape} (length: {len(raw_signal)}).")
        sys.exit(1)

    print(" ✓ Validated ECG signal: 3,600 samples @ 360 Hz")

    # 4. Apply Z-score normalization: (signal - mean) / (std + 1e-8)
    mean_val = float(np.mean(raw_signal))
    std_val = float(np.std(raw_signal))
    normalized_signal = (raw_signal - mean_val) / (std_val + 1e-8)
    print(" ✓ Applied per-signal Z-score normalization")

    # 5. Extract 43 features using feature_extraction.py
    features = extract_features_from_signal(normalized_signal)
    if len(features) != 43:
        print(f"❌ ERROR: Expected 43 features, but extracted {len(features)} features.")
        sys.exit(1)
    print(f" ✓ Extracted {len(features)} time, HRV, derivative, and FFT features")

    # Reshape features to 2D array: (1, 43)
    features_2d = features.reshape(1, -1)

    # 6. Load trained model & label mapping
    model_path = os.path.join("model", "hist_gradient_boosting.pkl")
    label_map_path = os.path.join("processed_data", "label_mapping.json")

    if not os.path.exists(model_path):
        print(f"❌ ERROR: Model file not found at '{model_path}'.")
        sys.exit(1)

    if not os.path.exists(label_map_path):
        print(f"❌ ERROR: Label mapping file not found at '{label_map_path}'.")
        sys.exit(1)

    with open(model_path, "rb") as f:
        model = pickle.load(f)

    with open(label_map_path, "r") as f:
        label_data = json.load(f)
        id_to_class = label_data["id_to_class"]

    # 7. Predict class & probabilities
    pred_class_id = int(model.predict(features_2d)[0])
    probs = model.predict_proba(features_2d)[0]

    predicted_label = id_to_class[str(pred_class_id)]
    confidence = float(probs[pred_class_id]) * 100.0

    print("\n" + "=" * 65)
    print("                    PREDICTION RESULTS                    ")
    print("=" * 65)
    print(f" 🎯 PREDICTED CLASS : {predicted_label}")
    print(f" 🆔 CLASS INDEX     : {pred_class_id}")
    print(f" 📈 CONFIDENCE      : {confidence:.2f}%")
    print("=" * 65)

    # 8. Display Top 5 Class Probabilities
    top5_indices = np.argsort(probs)[::-1][:5]
    print("\n--- TOP 5 CLASS PROBABILITIES ---")
    print(f"{'Rank':<5} | {'Class Name':<22} | {'Class ID':<8} | {'Probability':<12}")
    print("-" * 55)
    for rank, cid in enumerate(top5_indices, 1):
        cname = id_to_class[str(cid)]
        p_val = probs[cid] * 100.0
        print(f" {rank:<4} | {cname:<22} | {cid:<8} | {p_val:>6.2f}%")
    print("-" * 55)

    print("\n" + "=" * 65)
    print("⚠️ MEDICAL DISCLAIMER: This prediction is generated by a research")
    print("and hackathon benchmarking model. It is NOT intended or certified")
    print("for clinical or medical diagnostic use.")
    print("=" * 65 + "\n")

def main():
    parser = argparse.ArgumentParser(description="Standalone Inference Script for ECG Arrhythmia Classification")
    parser.add_argument("mat_file", type=str, help="Path to the .mat ECG file (containing 3600 samples)")
    args = parser.parse_args()

    predict_single_ecg(args.mat_file)

if __name__ == "__main__":
    main()
